name: flutter_native_image_v2
description: A flutter plugin which uses native iOS/Android to resize, compress or crop
version: 1.0.0+1
homepage: https://laurenscodes.space
issue_tracker: https://github.com/heathscliff334/flutter_native_image/issues

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
      ios:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
